name: Professional_CI_CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore GitHub-Actions.sln

      - name: Build
        run: dotnet build GitHub-Actions.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal