name: Professional_CI_CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn từ repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Bước 3: Khôi phục các gói phụ thuộc (Restore)
      - name: Restore
        run: dotnet restore GitHub-Actions.slnx

      # Bước 4: Biên dịch dự án (Build)
      - name: Build
        run: dotnet build GitHub-Actions.slnx --configuration Release --no-restore

      # Bước 5: Chạy các bài kiểm tra Unit Test (Test)
      - name: Test
        run: dotnet test GitHub-Actions.slnx --no-build --verbosity normal

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latestgit
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      # Bước 6: Thông báo triển khai
      - name: Notify Deployment
        run: echo "Deploying to server completed!"